### ISSUE TITLE
assets

### ISSUE THREAD

**Issue by zpl-zak** [zpl-c/texed#1]
![image](https://user-images.githubusercontent.com/9026786/118796542-ff717780-b89b-11eb-85ca-e5bbd60135e0.png)

**Comment by zaklaus** [comment]
![image](https://user-images.githubusercontent.com/9026786/118902426-eb6a5c00-b915-11eb-8569-593cbc8f4980.png)

**Comment by zaklaus** [comment]
![image](https://user-images.githubusercontent.com/9026786/119365626-69c95400-bcb0-11eb-9ed7-85b7aea25c4d.png)
